version: '3'

services:
    redis-master:
        image: redis:3
        command: redis-server
        networks:
            hostnet:
                ipv4_address: 172.17.0.2 # set the IP address for redis-master container
        restart: unless-stopped # always restart the container unless stopped explicitly

    redis-slave-1:
        image: redis:3
        command: redis-server --slaveof redis-master 6379
        links:
            - redis-master
        networks:
            hostnet:
                ipv4_address: 172.17.0.3 # set the IP address for redis-slave-1 container
        restart: unless-stopped

    redis-slave-2:
        image: redis:3
        command: redis-server --slaveof redis-master 6379
        links:
            - redis-master
        networks:
            hostnet:
                ipv4_address: 172.17.0.4 # set the IP address for redis-slave-2 container
        restart: unless-stopped

    sentinel-1:
        build: sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=500
            - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
        networks:
            hostnet:
                ipv4_address: 172.17.0.5 # set the IP address for sentinel-1 container
        restart: unless-stopped

    sentinel-2:
        build: sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=500
            - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
        networks:
            hostnet:
                ipv4_address: 172.17.0.6 # set the IP address for sentinel-2 container
        restart: unless-stopped

    sentinel-3:
        build: sentinel
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=500
            - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
        networks:
            hostnet:
                ipv4_address: 172.17.0.7 # set the IP address for sentinel-3 container
        restart: unless-stopped

    redis_cluster_app:
        build: app
        environment:
          - SENTINEL_DOWN_AFTER=5000
          - SENTINEL_FAILOVER=500
          - SENTINEL_QUORUM=2
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
        command: /bin/bash -c "echo 'Waiting for redis to run..' && sleep 60 && python redis_app.py"
        networks:
            hostnet:
                ipv4_address: 172.17.0.8 # set the IP address for redis_cluster_app container
        restart: unless-stopped

networks:
  hostnet: # define the host network
    external: true
